elasticsearch_host: "10.0.3.15"
prometheus_host: "10.0.3.11"
kibana_host: "10.0.4.13"
grafana_host: "10.0.4.19"
  
  
elasticsearch_version: "8.8.0"
kibana_version: "8.8.0"
filebeat_version: "8.8.0"
prometheus_version: "2.51.2"
node_exporter_version: "1.7.0"
nginx_log_exporter_version: "1.9.0"
grafana_version: "12.3.1"
  
website_local_path: "../website"
website_remote_path: "/var/www/html"
